create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  email text not null,
  username text not null,
  product text not null,
  claimed_discord_id text,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_lookup
  on public.orders (order_id, email, username);
