-- Cross-experience chat tables for the C++ overlay client.
-- Designed to be reachable from the desktop overlay using the Supabase
-- publishable (anon) key + a known room id. Room ids are UUIDs and act as
-- the shared secret between friends. RLS is intentionally permissive on
-- the messages table since the overlay does not yet hold a user JWT;
-- tighten this later when the launcher passes a real session.

create extension if not exists "pgcrypto";

create table if not exists public.chat_rooms (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now(),
  created_by text
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.chat_rooms(id) on delete cascade,
  author_id text not null,
  author_name text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_room_id_idx
  on public.chat_messages (room_id, id);

create index if not exists chat_messages_created_at_idx
  on public.chat_messages (created_at desc);

alter table public.chat_rooms enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "chat_rooms read" on public.chat_rooms;
create policy "chat_rooms read"
  on public.chat_rooms
  for select
  using (true);

drop policy if exists "chat_rooms insert" on public.chat_rooms;
create policy "chat_rooms insert"
  on public.chat_rooms
  for insert
  with check (true);

drop policy if exists "chat_messages read" on public.chat_messages;
create policy "chat_messages read"
  on public.chat_messages
  for select
  using (true);

drop policy if exists "chat_messages insert" on public.chat_messages;
create policy "chat_messages insert"
  on public.chat_messages
  for insert
  with check (
    char_length(body) between 1 and 2000
    and char_length(author_id) between 1 and 256
    and char_length(author_name) between 1 and 64
  );

-- A default seed room so the overlay can be tested immediately.
insert into public.chat_rooms (id, name, created_by)
values ('00000000-0000-0000-0000-00000000c1a7', 'Verdant Friends', 'system')
on conflict (id) do nothing;
