-- Unified schema sync for bot + web + launcher.

create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('percent', 'fixed')),
  value numeric(10,2) not null check (value >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gift_cards (
  id bigint generated by default as identity primary key,
  code text not null unique,
  product_hint text not null,
  amount_usd numeric(10,2) not null default 0,
  active boolean not null default true,
  redeemed boolean not null default false,
  redeemed_by text,
  redeemed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders
add column if not exists status text default 'completed',
add column if not exists download_url text,
add column if not exists license_key text,
add column if not exists claimed_role_id text,
add column if not exists hwid_lock text,
add column if not exists hwid_last_seen timestamptz;

create index if not exists idx_orders_license_key
on public.orders (license_key);

create index if not exists idx_promo_codes_code
on public.promo_codes (code);

create index if not exists idx_gift_cards_code
on public.gift_cards (code);

-- Required starter codes.
insert into public.promo_codes (code, type, value, active)
values
  ('VERDANT10', 'percent', 10, true),
  ('WELCOME15', 'percent', 15, true)
on conflict (code) do update
set type = excluded.type,
    value = excluded.value,
    active = excluded.active;

insert into public.gift_cards (code, product_hint, amount_usd, active, redeemed)
values
  ('TEST', 'fortnite', 500.00, true, false),
  ('GIFT-FN-500', 'fortnite', 500.00, true, false),
  ('GIFT-RBLX-500', 'roblox', 500.00, true, false),
  ('GIFT-CS2-500', 'cs2', 500.00, true, false)
on conflict (code) do update
set product_hint = excluded.product_hint,
    amount_usd = excluded.amount_usd,
    active = excluded.active;

-- Dashboard uses publishable key to read own orders.
alter table public.orders enable row level security;
drop policy if exists "orders_select_all" on public.orders;
drop policy if exists "orders_insert_all" on public.orders;
drop policy if exists "orders_update_all" on public.orders;

create policy "orders_select_all"
on public.orders
for select
to anon, authenticated
using (true);

create policy "orders_insert_all"
on public.orders
for insert
to anon, authenticated
with check (true);

create policy "orders_update_all"
on public.orders
for update
to anon, authenticated
using (true)
with check (true);
