create table if not exists public.accounts (
  id bigint generated by default as identity primary key,
  email text not null unique,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_accounts_email_username
  on public.accounts (email, username);
