create table if not exists public.promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('percent', 'fixed')),
  value numeric(10,2) not null check (value >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.gift_cards (
  id bigint generated by default as identity primary key,
  code text not null unique,
  product_hint text not null,
  active boolean not null default true,
  redeemed boolean not null default false,
  redeemed_by text,
  redeemed_at timestamptz,
  created_at timestamptz not null default now()
);

insert into public.promo_codes (code, type, value, active)
values
  ('VERDANT10', 'percent', 10, true),
  ('WELCOME15', 'percent', 15, true)
on conflict (code) do nothing;

insert into public.gift_cards (code, product_hint, active, redeemed)
values
  ('GIFT-FN-FREE', 'fortnite', true, false),
  ('GIFT-RBLX-FREE', 'roblox', true, false),
  ('GIFT-CS2-FREE', 'cs2', true, false)
on conflict (code) do nothing;
